// {
//     qobiliyat: "https://pokeapi.co/api/v2/ability/",
//      berry: "https://pokeapi.co/api/v2/berry/",
//      berry mustahkamligi: "https://pokeapi.co/api/v2/berry-firmness/",
//      berry-lavor "https://pokeapi.co/api/v2/berry-flavor/",
//      xarakteristikasi: "https://pokeapi.co/api/v2/characteristic/",
//      tanlov effekti: "https://pokeapi.co/api/v2/contest-effect/",
//      tanlov turi: "https://pokeapi.co/api/v2/contest-type/",
//      tuxum guruhi: "https://pokeapi.co/api/v2/egg-group/",
//      uchrashish sharti: "https://pokeapi.co/api/v2/encounter-condition/",
//      uchrashish-shart-qiymati: "https://pokeapi.co/api/v2/encounter-condition-value/",
//      uchrashish usuli: "https://pokeapi.co/api/v2/encounter-method/",
//      evolyutsiya zanjiri: "https://pokeapi.co/api/v2/evolution-chain/",
//      evolution-trigger: "https://pokeapi.co/api/v2/evolution-trigger/",
//      jins: "https://pokeapi.co/api/v2/gender/",
//      avlod: "https://pokeapi.co/api/v2/generation/",
//      o'sish sur'ati: "https://pokeapi.co/api/v2/growth-rate/",
//      element: "https://pokeapi.co/api/v2/item/",
//      element atributi: "https://pokeapi.co/api/v2/item-attribute/",
//      item-category: "https://pokeapi.co/api/v2/item-category/",
//      item-fling-effect: "https://pokeapi.co/api/v2/item-fling-effect/",
//      item-pocket: "https://pokeapi.co/api/v2/item-pocket/",
//      til: "https://pokeapi.co/api/v2/language/",
//      joylashuv: "https://pokeapi.co/api/v2/location/",
//      joylashuv hududi: "https://pokeapi.co/api/v2/location-area/",
//      mashina: "https://pokeapi.co/api/v2/machine/",
//      ko'chirish: "https://pokeapi.co/api/v2/move/",
//      harakat kasalligi: "https://pokeapi.co/api/v2/move-ailment/",
//      move-battle-style: "https://pokeapi.co/api/v2/move-battle-style/",
//      ko'chirish-toifasi: "https://pokeapi.co/api/v2/move-category/",
//      move-damage-class: "https://pokeapi.co/api/v2/move-damage-class/",
//      move-learn-method: "https://pokeapi.co/api/v2/move-learn-method/",
//      : "https://pokeapi.co/api/v2/move-target/",
//      tabiat: "https://pokeapi.co/api/v2/nature/",
//      pal-park-area: "https://pokeapi.co/api/v2/pal-park-area/",
//      pokeathlon-stat: "https://pokeapi.co/api/v2/pokeathlon-stat/",
//      pokedex: "https://pokeapi.co/api/v2/pokedex/",
//      pokemon: "https://pokeapi.co/api/v2/pokemon/",
//      pokemon rangi: "https://pokeapi.co/api/v2/pokemon-color/",
//      pokemon-form: "https://pokeapi.co/api/v2/pokemon-form/",
//      pokemon-habitat: "https://pokeapi.co/api/v2/pokemon-habitat/",
//      pokemon shakli: "https://pokeapi.co/api/v2/pokemon-shape/",
//      pokemon turlari: "https://pokeapi.co/api/v2/pokemon-species/",
//      mintaqa: "https://pokeapi.co/api/v2/region/",
//      stat: "https://pokeapi.co/api/v2/stat/",
//      super-tanlov effekti: "https://pokeapi.co/api/v2/super-contest-effect/",
//      turi: "https://pokeapi.co/api/v2/type/",
//      versiya: "https://pokeapi.co/api/v2/version/",
//      versiya guruhi: "https://pokeapi.co/api/v2/version-group/"
// }